apiVersion: v1
kind: Service
metadata:
  name: evidently-service-svc
  namespace: evidently
spec:
  type: NodePort
  selector:
    app: evidently-service
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085
    nodePort: 30008