apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidently-service
  namespace: evidently
  labels:
    app: evidently-service
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: evidently-service
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: evidently-service
    spec:
      containers:
      - name: evidently-service
        imagePullPolicy: Never
        image: evidently-service:latest
        ports:
        - containerPort: 8085
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 120
          timeoutSeconds: 10
        resources:
          requests:
            memory: "2000Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "4000m"